Support for software/virtual sensors
aleksamagicka/aquacomputer_d5next-hwmon pull request #24
Opened 2022-08-04 17:21 UTC by aleksamagicka

(Initial) Support for virtual software sensors of the Octo, Quadro, Farbwerk 360 and D5 Next.

TODO before merging:

- [x] Read and expose virtual sensors from the sensors report
- [ ] Implement writing to sysfs entries and saving them to the device (need to RE offsets)

2022-08-06 19:36 UTC, leoratte requested changes

2022-08-06 19:36 UTC, leoratte commented on aquacomputer_d5next.c
> +		if (channel < priv->num_virtual_temp_sensors)
should be `if (channel < priv->num_temp_sensors + priv->num_virtual_temp_sensors)` to accommodate for all virtual sensors

2022-08-06 19:36 UTC, leoratte commented on aquacomputer_d5next.c
> +			*str = priv->virtual_temp_label[channel - priv->num_temp_sensors - 1];
remove  `-1` as channel starts at 0 and so the first virtual sensor would get virtual_temp_label[-1]

2022-08-07 03:21 UTC, aleksamagicka commented
Thanks, fixed these oversights. I distinctly remember writing that and feeling something was off :sweat_smile:

2022-08-16 18:02 UTC, merged

2022-08-16 18:03 UTC, aleksamagicka commented
Note: it looks like virtual temp sensors automatically expire on the device after 10-15 seconds of no further updates.