Add option to change multiple ctrl values at once
aleksamagicka/aquacomputer_d5next-hwmon pull request #47
Opened 2022-11-02 21:51 UTC by leoratte

Adds the option to change multiple control values at once with aqc_set_ctrl_vars. This new function accepts three arrays for val, offset and size and size of the arrays.

Use this approach instead of #43.

2022-11-06 19:28 UTC, aleksamagicka commented
Thanks, will look into this ASAP.

2022-11-07 12:25 UTC, aleksamagicka requested changes
Comments enclosed.

Side note: there's no need to force push every time. All commits will get squashed either way when I merge them and it's easier to look at incremental changes than re-read the whole thing each time and try to find the difference. :smiley:

2022-11-07 12:25 UTC, aleksamagicka commented on aquacomputer_d5next.c
> +static int aqc_set_buffer_val(u8 buffer[], int offset, long val, size_t size)
`u8 *buffer` to be consistent

2022-11-07 12:25 UTC, aleksamagicka commented on aquacomputer_d5next.c
> +	int offset[3];
Name these `ctrl_values_offsets`, `ctrl_values`, `ctrl_values_sizes` or similar, so it's clear what they are for. And add a comment above that they're for setting multiple values at once in the ctrl report.

2022-11-07 12:25 UTC, aleksamagicka commented on aquacomputer_d5next.c
> +static int aqc_set_ctrl_vals(struct aqc_data *priv, int offset[], long val[],
As far as I can see `aqc_set_ctrl_val()` can be refactored to use this with size of 1? And I'd name the three array parameters in plural, they hold multiple values after all.

2022-11-07 17:51 UTC, leoratte commented
I've addressed all of your comments.

2022-11-08 15:17 UTC, merged